import logging
from datetime import datetime
from app.services.endpoint_summary_service import get_endpoint_summaries

logger = logging.getLogger(__name__)

def build_health_report_subject(healthy_count: int, total_count: int) -> str:
    """
    Builds the subject line for the health report email.
    """
    return f"📊 API Health Report: {healthy_count}/{total_count} Systems Operational"

def build_health_report_html(
    total_apis: int, 
    healthy_apis: int, 
    failed_apis: int, 
    avg_response_time: float, 
    failed_api_list: list, 
    timestamp: str
) -> str:
    """
    Builds the professional HTML body for the health report.
    """
    failed_rows = ""
    if failed_api_list:
        for api in failed_api_list:
            name = getattr(api, "name", "Unknown API")
            message = getattr(api, "last_message", "N/A")
            failed_rows += f"""
            <tr>
                <td style="padding: 8px; border-bottom: 1px solid #eee;">{name}</td>
                <td style="padding: 8px; border-bottom: 1px solid #eee; color: #d9534f;">{message}</td>
            </tr>
            """
    else:
        failed_rows = """
        <tr>
            <td colspan="2" style="padding: 12px; border-bottom: 1px solid #eee; text-align: center; color: #5cb85c; font-weight: bold;">
                🎉 All Monitored APIs are Operational!
            </td>
        </tr>
        """
        
    color_header = "#28a745" if failed_apis == 0 else "#ffc107" if healthy_apis > 0 else "#dc3545"

    return f"""
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background-color: {color_header}; color: white; padding: 15px; text-align: center;">
            <h2 style="margin: 0; font-size: 24px;">Daily API Health Report</h2>
        </div>
        <div style="padding: 20px;">
            <table style="width: 100%; border-collapse: collapse; text-align: left; margin-bottom: 25px;">
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; width: 50%;">Total Monitored APIs</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{total_apis}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Healthy APIs (PASS)</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; color: #28a745; font-weight: bold;">{healthy_apis}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Failed APIs (FAIL)</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; color: #dc3545; font-weight: bold;">{failed_apis}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Average Response Time</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{avg_response_time:.2f} ms</td>
                </tr>
                <tr>
                    <td style="padding: 8px; font-weight: bold;">Generated At (UTC)</td>
                    <td style="padding: 8px;">{timestamp}</td>
                </tr>
            </table>

            <h3 style="margin-top: 0; color: #444;">Failing APIs Details</h3>
            <table style="width: 100%; border-collapse: collapse; text-align: left; background-color: #fdfdfd;">
                <thead>
                    <tr>
                        <th style="padding: 8px; border-bottom: 2px solid #ddd; width: 35%;">API Name</th>
                        <th style="padding: 8px; border-bottom: 2px solid #ddd;">Failure Reason</th>
                    </tr>
                </thead>
                <tbody>
                    {failed_rows}
                </tbody>
            </table>
        </div>
        <div style="background-color: #f9f9f9; padding: 12px; text-align: center; font-size: 12px; color: #777; border-top: 1px solid #eee;">
            Generated by API Endpoint Testing Platform
        </div>
    </div>
    """

from app.services.notification_recipient_service import get_active_notification_users
from app.services.resend_service import send_email_via_resend

def generate_health_report() -> tuple[str, str]:
    """
    Computes all health metrics from the endpoint summaries, generates the HTML report,
    and sends it to all active notification users.
    Returns: 
        (subject, html_content)
    """
    summaries = get_endpoint_summaries()
    
    total_apis = len(summaries)
    healthy_apis = 0
    failed_apis = 0
    total_response_time = 0.0
    valid_response_times_count = 0
    failed_api_list = []
    
    for summary in summaries:
        status = getattr(summary, "status", "NOT_TESTED")
        response_time = getattr(summary, "response_time_ms", 0)
        
        if status == "PASS":
            healthy_apis += 1
        elif status == "FAIL":
            failed_apis += 1
            failed_api_list.append(summary)
            
        # Exclude NOT_TESTED from average response time calculation
        if status != "NOT_TESTED":
            total_response_time += (response_time or 0)
            valid_response_times_count += 1
            
    avg_response_time = (total_response_time / valid_response_times_count) if valid_response_times_count > 0 else 0.0
    
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    
    subject = build_health_report_subject(healthy_apis, total_apis)
    html = build_health_report_html(
        total_apis=total_apis,
        healthy_apis=healthy_apis,
        failed_apis=failed_apis,
        avg_response_time=avg_response_time,
        failed_api_list=failed_api_list,
        timestamp=timestamp
    )
    
    active_users = get_active_notification_users()
    if active_users:
        print(f"\nFound {len(active_users)} active users.\n")
        print("Sending health report to:")
        for user in active_users:
            print(f"- {user.get('name')} ({user.get('email')})")
        print()
        
        for user in active_users:
            recipient = user.get("email")
            if not recipient:
                continue
            try:
                send_email_via_resend(
                    to_address=recipient,
                    subject=subject,
                    html_content=html
                )
            except Exception as e:
                logger.error(f"Failed to send health report to {recipient}: {e}")
    else:
        logger.info("No active notification users found for health report.")
    
    return subject, html
