import logging
from datetime import datetime, timezone, timedelta
from app.services.resend_service import send_email_via_resend
from app.repositories.alert_state_repository import get_alert_state, update_last_alert_sent

from app.services.notification_recipient_service import get_active_notification_users

logger = logging.getLogger(__name__)

DEFAULT_ALERT_COOLDOWN_MINUTES = 30

def build_failure_subject(endpoint_name: str) -> str:
    return f"🚨 API Alert: {endpoint_name} FAILED"

def build_failure_email_html(endpoint: dict, validation_result: dict, response_time_ms: float, response_status_code: int) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    test_type = endpoint.get("test_type", "Manual/Scheduled")
    
    return f"""
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #f8d7da; color: #721c24; padding: 15px; text-align: center; border-bottom: 1px solid #f5c6cb;">
            <h2 style="margin: 0; font-size: 24px;">API Test Failure</h2>
            <span style="display: inline-block; background-color: #dc3545; color: white; padding: 4px 10px; border-radius: 4px; font-weight: bold; margin-top: 10px;">FAILED</span>
        </div>
        <div style="padding: 20px;">
            <table style="width: 100%; border-collapse: collapse; text-align: left;">
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; width: 35%;">API Name</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{endpoint.get('name', 'N/A')}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">API URL</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{endpoint.get('url', 'N/A')}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">HTTP Method</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{endpoint.get('method', 'GET').upper()}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">HTTP Status Code</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{response_status_code}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Response Time</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{response_time_ms} ms</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Failure Reason</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; color: #d9534f;">{validation_result.get('message', 'Unknown')}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Test Type</td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{test_type}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; font-weight: bold;">Timestamp</td>
                    <td style="padding: 8px;">{timestamp}</td>
                </tr>
            </table>
        </div>
        <div style="background-color: #f9f9f9; padding: 12px; text-align: center; font-size: 12px; color: #777; border-top: 1px solid #eee;">
            Generated by API Endpoint Testing Platform
        </div>
    </div>
    """

def process_test_result_for_notification(endpoint: dict, validation_result: dict, response_time_ms: float, response_status_code: int):
    """
    Evaluates the test result and decides whether an email notification should be sent,
    respecting a cooldown period to prevent spam.
    """
    if not validation_result.get("passed", True):
        api_name = endpoint.get('name', 'Unknown API')
            
        # --- Cooldown Logic ---
        now_utc = datetime.now(timezone.utc)
        alert_state = get_alert_state(api_name)
        
        if alert_state and "last_alert_sent_at" in alert_state:
            last_sent = alert_state["last_alert_sent_at"]
            # MongoDB datetime might be naive, so we make it UTC aware if necessary
            if last_sent.tzinfo is None:
                last_sent = last_sent.replace(tzinfo=timezone.utc)
                
            cooldown_period = timedelta(minutes=DEFAULT_ALERT_COOLDOWN_MINUTES)
            if (now_utc - last_sent) < cooldown_period:
                logger.info(f"Alert suppressed for {api_name}: Cooldown period of {DEFAULT_ALERT_COOLDOWN_MINUTES} minutes has not expired.")
                return

        active_users = get_active_notification_users()
        if not active_users:
            logger.debug(f"Test failed for {api_name}, but no active users found.")
            return
            
        print(f"\nFound {len(active_users)} active users.\n")
        print("Sending failure alert to:")
        for user in active_users:
            print(f"- {user.get('name')} ({user.get('email')})")
        print()

        # --- Email Dispatch ---
        subject = build_failure_subject(api_name)
        html_content = build_failure_email_html(
            endpoint=endpoint, 
            validation_result=validation_result, 
            response_time_ms=response_time_ms, 
            response_status_code=response_status_code
        )
        
        logger.info(f"Triggering email notification for failed endpoint: {api_name}")
        
        any_success = False
        for user in active_users:
            recipient = user.get("email")
            if not recipient:
                continue
            try:
                send_result = send_email_via_resend(
                    to_address=recipient,
                    subject=subject,
                    html_content=html_content
                )
                if send_result:
                    any_success = True
                    print(f"Email sent successfully to {recipient}.")
            except Exception as e:
                logger.error(f"Failed to send email to {recipient}: {e}")
        
        # Only update the timestamp if at least one email was successfully sent
        if any_success:
            update_last_alert_sent(api_name, now_utc)

